import { Router } from 'express';
import pool from '../db';
import { requireAuth } from '../middleware/auth';

const router = Router();

const mapPlatform = (r: any) => ({ id: r.id, name: r.name, slug: r.slug, logoUrl: r.logo_url, linkUrl: r.link_url, published: r.published, sortOrder: r.sort_order });
const mapPlan = (r: any) => ({ id: r.id, name: r.name, price: r.price, period: r.period, description: r.description, features: r.features || [], ctaText: r.cta_text, highlighted: r.highlighted, published: r.published, sortOrder: r.sort_order });
const mapCategory = (r: any) => ({ id: r.id, name: r.name, slug: r.slug });
const mapWork = (r: any) => ({ id: r.id, title: r.title, slug: r.slug, categoryId: r.category_id, imageUrl: r.image_url, galleryUrls: r.gallery_urls || [], description: r.description, altText: r.alt_text, published: r.published, featured: r.featured, sortOrder: r.sort_order });
const mapLegal = (r: any) => ({ slug: r.slug, title: r.title, content: r.content, updatedAt: r.updated_at });
const mapSeo = (r: any) => ({ id: r.id, path: r.path, metaTitle: r.meta_title, metaDescription: r.meta_description, metaKeywords: r.meta_keywords, ogTitle: r.og_title, ogDescription: r.og_description, ogImage: r.og_image, twitterTitle: r.twitter_title, twitterDescription: r.twitter_description, canonicalUrl: r.canonical_url, structuredData: r.structured_data || {}, noindex: r.noindex });

router.get('/platforms', async (_req, res) => { const r = await pool.query('SELECT * FROM platforms ORDER BY sort_order, id'); res.json(r.rows.map(mapPlatform)); });
router.post('/platforms', requireAuth, async (req, res) => {
  try { const { name, slug, logoUrl, linkUrl, published, sortOrder } = req.body; const r = await pool.query('INSERT INTO platforms (name, slug, logo_url, link_url, published, sort_order) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *', [name, slug, logoUrl ?? '', linkUrl ?? '', published ?? true, sortOrder ?? 0]); res.status(201).json(mapPlatform(r.rows[0])); } catch (e: any) { res.status(e.code === '23505' ? 409 : 500).json({ error: e.code === '23505' ? 'Slug already exists' : 'Internal server error' }); }
});
router.patch('/platforms/:id', requireAuth, async (req, res) => {
  const { name, slug, logoUrl, linkUrl, published, sortOrder } = req.body; const r = await pool.query('UPDATE platforms SET name=COALESCE($1,name), slug=COALESCE($2,slug), logo_url=COALESCE($3,logo_url), link_url=COALESCE($4,link_url), published=COALESCE($5,published), sort_order=COALESCE($6,sort_order) WHERE id=$7 RETURNING *', [name, slug, logoUrl, linkUrl, published, sortOrder, req.params.id]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapPlatform(r.rows[0]));
});
router.delete('/platforms/:id', requireAuth, async (req, res) => { await pool.query('DELETE FROM platforms WHERE id=$1', [req.params.id]); res.json({ success: true }); });

router.get('/pricing', async (_req, res) => { const r = await pool.query('SELECT * FROM pricing_plans ORDER BY sort_order, id'); res.json(r.rows.map(mapPlan)); });
router.post('/pricing', requireAuth, async (req, res) => { const { name, price, period, description, features, ctaText, highlighted, published, sortOrder } = req.body; const r = await pool.query('INSERT INTO pricing_plans (name, price, period, description, features, cta_text, highlighted, published, sort_order) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *', [name, price ?? '', period ?? 'One-time', description ?? '', JSON.stringify(features ?? []), ctaText ?? 'Get started', highlighted ?? false, published ?? true, sortOrder ?? 0]); res.status(201).json(mapPlan(r.rows[0])); });
router.patch('/pricing/:id', requireAuth, async (req, res) => { const { name, price, period, description, features, ctaText, highlighted, published, sortOrder } = req.body; const r = await pool.query('UPDATE pricing_plans SET name=COALESCE($1,name), price=COALESCE($2,price), period=COALESCE($3,period), description=COALESCE($4,description), features=COALESCE($5,features), cta_text=COALESCE($6,cta_text), highlighted=COALESCE($7,highlighted), published=COALESCE($8,published), sort_order=COALESCE($9,sort_order) WHERE id=$10 RETURNING *', [name, price, period, description, features ? JSON.stringify(features) : null, ctaText, highlighted, published, sortOrder, req.params.id]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapPlan(r.rows[0])); });
router.delete('/pricing/:id', requireAuth, async (req, res) => { await pool.query('DELETE FROM pricing_plans WHERE id=$1', [req.params.id]); res.json({ success: true }); });

router.get('/graphic-categories', async (_req, res) => { const r = await pool.query('SELECT * FROM graphic_categories ORDER BY name'); res.json(r.rows.map(mapCategory)); });
router.post('/graphic-categories', requireAuth, async (req, res) => { const r = await pool.query('INSERT INTO graphic_categories (name, slug) VALUES ($1,$2) RETURNING *', [req.body.name, req.body.slug]); res.status(201).json(mapCategory(r.rows[0])); });
router.patch('/graphic-categories/:id', requireAuth, async (req, res) => { try { const r = await pool.query('UPDATE graphic_categories SET name=COALESCE($1,name), slug=COALESCE($2,slug) WHERE id=$3 RETURNING *', [req.body.name, req.body.slug, req.params.id]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapCategory(r.rows[0])); } catch (err: any) { res.status(err.code === '23505' ? 409 : 500).json({ error: err.code === '23505' ? 'Slug already exists' : 'Internal server error' }); } });
router.delete('/graphic-categories/:id', requireAuth, async (req, res) => { await pool.query('DELETE FROM graphic_categories WHERE id=$1', [req.params.id]); res.json({ success: true }); });
router.get('/graphic-works', async (_req, res) => { const r = await pool.query('SELECT * FROM graphic_works ORDER BY sort_order, id'); res.json(r.rows.map(mapWork)); });
router.post('/graphic-works', requireAuth, async (req, res) => { const { title, slug, categoryId, imageUrl, galleryUrls, description, altText, published, featured, sortOrder } = req.body; if (featured) { const count = await pool.query('SELECT COUNT(*)::int AS count FROM graphic_works WHERE featured = true'); if (count.rows[0].count >= 6) return res.status(409).json({ error: 'A maximum of 6 featured graphic works is allowed' }); } const r = await pool.query('INSERT INTO graphic_works (title, slug, category_id, image_url, gallery_urls, description, alt_text, published, featured, sort_order) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *', [title, slug, categoryId || null, imageUrl ?? '', JSON.stringify(galleryUrls ?? []), description ?? '', altText ?? '', published ?? false, featured ?? false, sortOrder ?? 0]); res.status(201).json(mapWork(r.rows[0])); });
router.patch('/graphic-works/:id', requireAuth, async (req, res) => { const { title, slug, categoryId, imageUrl, galleryUrls, description, altText, published, featured, sortOrder } = req.body; if (featured) { const count = await pool.query('SELECT COUNT(*)::int AS count FROM graphic_works WHERE featured = true AND id <> $1', [req.params.id]); if (count.rows[0].count >= 6) return res.status(409).json({ error: 'A maximum of 6 featured graphic works is allowed' }); } const r = await pool.query('UPDATE graphic_works SET title=COALESCE($1,title), slug=COALESCE($2,slug), category_id=COALESCE($3,category_id), image_url=COALESCE($4,image_url), gallery_urls=COALESCE($5,gallery_urls), description=COALESCE($6,description), alt_text=COALESCE($7,alt_text), published=COALESCE($8,published), featured=COALESCE($9,featured), sort_order=COALESCE($10,sort_order) WHERE id=$11 RETURNING *', [title, slug, categoryId, imageUrl, galleryUrls ? JSON.stringify(galleryUrls) : null, description, altText, published, featured, sortOrder, req.params.id]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapWork(r.rows[0])); });
router.delete('/graphic-works/:id', requireAuth, async (req, res) => { await pool.query('DELETE FROM graphic_works WHERE id=$1', [req.params.id]); res.json({ success: true }); });

router.get('/legal', async (_req, res) => { const r = await pool.query('SELECT * FROM legal_pages ORDER BY slug'); res.json(r.rows.map(mapLegal)); });
router.patch('/legal/:slug', requireAuth, async (req, res) => { const r = await pool.query('UPDATE legal_pages SET title=COALESCE($1,title), content=COALESCE($2,content), updated_at=NOW() WHERE slug=$3 RETURNING *', [req.body.title, req.body.content, req.params.slug]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapLegal(r.rows[0])); });
router.get('/seo', async (_req, res) => { try { const r = await pool.query('SELECT * FROM seo_pages ORDER BY path'); res.json(r.rows.map(mapSeo)); } catch (e) { res.status(500).json({ error: 'Internal server error' }); } });
router.post('/seo', requireAuth, async (req, res) => { try { const { path, metaTitle, metaDescription, metaKeywords, ogTitle, ogDescription, ogImage, twitterTitle, twitterDescription, canonicalUrl, structuredData, noindex } = req.body; if (!path) return res.status(400).json({ error: 'path is required' }); const r = await pool.query('INSERT INTO seo_pages (path, meta_title, meta_description, meta_keywords, og_title, og_description, og_image, twitter_title, twitter_description, canonical_url, structured_data, noindex) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *', [path, metaTitle ?? '', metaDescription ?? '', metaKeywords ?? '', ogTitle ?? '', ogDescription ?? '', ogImage ?? '', twitterTitle ?? '', twitterDescription ?? '', canonicalUrl ?? '', structuredData ? JSON.stringify(structuredData) : '{}', noindex ?? false]); res.status(201).json(mapSeo(r.rows[0])); } catch (e: any) { res.status(e.code === '23505' ? 409 : 500).json({ error: e.code === '23505' ? 'A page with that path already exists' : 'Internal server error' }); } });
router.patch('/seo/:id', requireAuth, async (req, res) => { try { const { path, metaTitle, metaDescription, metaKeywords, ogTitle, ogDescription, ogImage, twitterTitle, twitterDescription, canonicalUrl, structuredData, noindex } = req.body; const r = await pool.query('UPDATE seo_pages SET path=COALESCE($1,path), meta_title=COALESCE($2,meta_title), meta_description=COALESCE($3,meta_description), meta_keywords=COALESCE($4,meta_keywords), og_title=COALESCE($5,og_title), og_description=COALESCE($6,og_description), og_image=COALESCE($7,og_image), twitter_title=COALESCE($8,twitter_title), twitter_description=COALESCE($9,twitter_description), canonical_url=COALESCE($10,canonical_url), structured_data=COALESCE($11,structured_data), noindex=COALESCE($12,noindex), updated_at=NOW() WHERE id=$13 RETURNING *', [path, metaTitle, metaDescription, metaKeywords, ogTitle, ogDescription, ogImage, twitterTitle, twitterDescription, canonicalUrl, structuredData ? JSON.stringify(structuredData) : null, noindex, req.params.id]); if (!r.rows[0]) return res.status(404).json({ error: 'Not found' }); res.json(mapSeo(r.rows[0])); } catch(e) { res.status(500).json({ error: 'Internal server error' }); } });
router.delete('/seo/:id', requireAuth, async (req, res) => { try { await pool.query('DELETE FROM seo_pages WHERE id=$1', [req.params.id]); res.json({ success: true }); } catch(e) { res.status(500).json({ error: 'Internal server error' }); } });

export default router;