interface HeroRichTextProps {
  html: string;
}

/** Allow only the simple formatting generated by the CMS editor. */
function sanitizeHeroHtml(html: string) {
  const withLineBreaks = html
    .replace(/<(?:div|p)\b[^>]*>/gi, '<br>')
    .replace(/<\/(?:div|p)\s*>/gi, '')
    .replace(/^(?:\s*<br\s*\/?>\s*)+/i, '')
    .replace(/(?:\s*<br\s*\/?>\s*)+$/i, '');

  return withLineBreaks
    .replace(/<(?!\/?(?:br|span|mark|b|strong)(?:\s[^>]*)?>)[^>]+>/gi, '')
    .replace(/\son\w+=(?:"[^"]*"|'[^']*')/gi, '')
    .replace(/\sstyle=(?:"[^"]*"|'[^']*')/gi, (match) =>
      /background-color|color/i.test(match) ? match : '',
    );
}

export function HeroRichText({ html }: HeroRichTextProps) {
  return <span dangerouslySetInnerHTML={{ __html: sanitizeHeroHtml(html) }} />;
}