interface HeroRichTextProps {
  html: string;
}

/** Allow only the simple formatting generated by the CMS editor. */
function sanitizeHeroHtml(html: string) {
  return html
    .replace(/<(?!\/?(?:br|span|mark|b|strong)(?:\s[^>]*)?>)[^>]+>/gi, '')
    .replace(/\son\w+=(?:"[^"]*"|'[^']*')/gi, '')
    .replace(/\sstyle=(?:"[^"]*"|'[^']*')/gi, (match) =>
      /background-color|color/i.test(match) ? match : '',
    );
}

export function HeroRichText({ html }: HeroRichTextProps) {
  return <span dangerouslySetInnerHTML={{ __html: sanitizeHeroHtml(html) }} />;
}